# Generated by Django 4.2 on 2023-05-01 09:03

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="board/"
            ),
        ),
    ]
