# Generated by Django 4.2 on 2023-05-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_board_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
